### ISSUE TITLE
Traitor-bought items not appearing

### ISSUE THREAD

**Issue by IMVader** [Spoffy/LLA-Station-13#159]
http://oi62.tinypic.com/21l69up.jpg

I (Mankey Man) had bought one Emag and one Singularity Beacon. Lucy had bought at least Thermals, dunno what else. As our bodies were destroyed by singularity, the information was deleted and didn't appear at the end of the round.

**Comment by FlavoredCactus** [comment]
https://github.com/Spoffy/LLA-Station-13/wiki/Bug-Report-Template
