### ISSUE TITLE
Cyborg Upload console spamming errors when clicked.

### ISSUE THREAD

**Issue by vylne** [Spoffy/LLA-Station-13#160]
Objects or Mechanics Involved: Cyborg Upload Console

Brief Description (include as much detail as possible): It was the beginning of the round, and I headed into AI upload to see if any silicons existed, I clicked the cyborg upload console and I was barraged with "usage:  parameter#Sorry, the following is not valid: Earl"
What did you expect to happen?: I expected a message saying that either no borgs were detected, or that a borg was detected

What happened instead?:I was barraged with the error message "usage:  parameter#Sorry, the following is not valid: Earl"

Has this occurred before?: This has occurred before, the last time I did the exact same steps, I was barraged with the error message as well.

What were you doing beforehand?: The round just stopped, I turned off the upload turrets, went in and it happened.

Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.): For looking into the logs, the issue occurred at the beginning of the round starting at roughly 6:20AM EST 1/4/2015

**Comment by Setheri** [comment]
What time zone are you in?
