### ISSUE TITLE
Exosuit Fabricator bug?

### ISSUE THREAD

**Issue by KawaiiUguuDesuKa** [Spoffy/LLA-Station-13#175]
So I was roboticist, noticed after a few minutes of round start that the cyborg recipe was changed to a match stick, this was even after I had made a cyborg head with that exosuit fabricator before.
Heres a screenshot of the recipe changed.
![wot](https://cloud.githubusercontent.com/assets/10589141/5794684/a6dfa59e-9f2d-11e4-9f46-687ff60949bd.png)

**Comment by FlavoredCactus** [comment]
How can i replicate this? what did you do that round?

**Comment by KawaiiUguuDesuKa** [comment]
The things I did prior to this happening was manually add each item of cyborg to queue and then process the queue. Besides that I have no idea.

**Comment by Setheri** [comment]
I've reviewed the code but I can't find what could be causing it. We need better info and a way to reproduce the issue before we'll be able to track it down unfortunately.
