### ISSUE TITLE
FAT

### ISSUE THREAD

**Issue by Drad3n** [Spoffy/LLA-Station-13#191]
NOT WORK FIX GET FAT AM NOT GET FAT, SAY YOU FEEL BLUBBERY, BUT AM NOT BLUBBERY!

**Comment by FlavoredCactus** [comment]
There is no tag for "Not a bug" but this is not a bug.

This is not a bug and is intended. the side effects of being fat are a "They look quite chubb", FAT mutation flag (when you eat a mint you gib), slow movement, high temperature. There is no icon for being fat and no check to pop off clothing.
