### ISSUE TITLE
Pinpointer not showing shunted APC location correctly

### ISSUE THREAD

**Issue by halueryphi** [Spoffy/LLA-Station-13#194]
Objects or Mechanics Involved: Pinpointer, Malf AI, Shunted APC
Brief Description (include as much detail as possible): When using a pinpointer to locate a malf AI's shunted APC, it sometimes does not point to the right direction, as in, if a shunted apc is in Atmos, the pinpointer will point below the AI for some reason.
What did you expect to happen?: It would show the correct position for the shunted APC
What happened instead?: It shows some random position. Possibly always below the AI.
Has this occurred before?: Once I think.
What were you doing beforehand?: Just using the pinpointer to locate the APC
Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.): Nope.

**Comment by FlavoredCactus** [comment]
Have you tried turning it off and on?

**Comment by halueryphi** [comment]
You know what's funny? I actually thought that would be the solution, but it seems so ironic..

**Comment by AquaDraco** [comment]
Right, forgot to mention. I tried testing for this last month, but couldn't reproduce the issue. The pinpointer is fine as long as you remember to reset it by turning it on and off every time the AI changes cores.
