### ISSUE TITLE
Airlock Sound

### ISSUE THREAD

**Issue by Agent1667** [Spoffy/LLA-Station-13#200]
Objects or Mechanics Involved: Airlocks.

Brief Description (include as much detail as possible): So, I manually close an airlock (It makes the airlock closing sound), but seconds later (Probably when the door would naturally close), I hear it again.

What did you expect to happen?: To not hear the airlock sound again.

What happened instead?: I heard the airlock sound again.

Has this occurred before?: All the time.

What were you doing beforehand?: Opening an airlock, leaving and entering a room.

Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.): I'm pretty sure this happen at every airlock, not certain though. I know for sure: Telecoms, Maintenance, Clown Office, Mime Office, Engineering. 

How to replicate: Open a door and click to manually close it, then wait at least 10 seconds. The sound should happen again.

**Comment by FlavoredCactus** [comment]
Can't seem to reproduce this, you said you play with a high ping, try this when your ping isn't off the charts and let me know what happens.
