### ISSUE TITLE
MMI eye damage bug

### ISSUE THREAD

**Issue by IMVader** [Spoffy/LLA-Station-13#237]
Objects or Mechanics Involved: MMI-with-brain and screwdriver aimed at the eyes.
Brief Description (include as much detail as possible): I was a borg and was blown. The MMI that was left was picked up and a screwdriver was repeatedly applied to it, aimed at the eyes. It happened the same as it would have happened to an eye-unprotected living crew member, resulting in the same attack messages and nearsightedness as a result. The foggy effect did not disappear, though.
What did you expect to happen?: Screwdrivers to be ineffective at causing eye damage to brains-in-MMIs.
What happened instead?: Eye damage was dealt resulting in both nearsightedness and the persistent foggy effect that comes while being stabbed in the eyes.
Has this occurred before?: Only time it happened to me, have not tested further.
What were you doing beforehand?: Joining the round as assistant, being borged and then being a borg.
Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.):
http://gyazo.com/ab04458673cd588419da9b014227ff21
http://gyazo.com/aa7103c77d168706b102bdb0efc8d040

**Comment by Setheri** [comment]
You forgot to include the part where I blew you up ;)
