### ISSUE TITLE
Space Pull Directions

### ISSUE THREAD

**Issue by Mindtrixx** [Spoffy/LLA-Station-13#292]
Objects or Mechanics Involved: Space and its pull
Brief Description (include as much detail as possible): When pulling one way the space pull defaults back to its last direction. IE body is spaced south, it will keep moving south after being pulled north.
What did you expect to happen?: Bodies to follow normal space physics.
What happened instead?: They didn't
Has this occurred before?: Yes, its a constant thing. I'm unsure if its a bug but I rather make a report before a suggestion post.
What were you doing beforehand?: Observing a hobbit and was reminded this is still a thing.
Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.): Butts

**Comment by FlavoredCactus** [comment]
I'm unsure which one it is, but I'll look it over and find that out sometime soon.

**Comment by FlavoredCactus** [comment]
this (and other suggestions should be brought to the forums.
