### ISSUE TITLE
Droppers Bugged

### ISSUE THREAD

**Issue by Lichling** [Spoffy/LLA-Station-13#310]
So I've known this has been an issue for a while but forgot to post about it. Droppers are bugged and their icon state doesn't change to empty upon using it on a hydrotray. I have to use the dropper (that still has a filled icon state despite being empty) on a beaker to fix it. It gets really annoying after have done it hundreds of times. Fix please!

**Comment by Setheri** [comment]
I thought I found where the issue was and told you to try fixing it as a coding exercise? it looked like a couple lines just needed to be added lower in the code.

**Comment by FlavoredCactus** [comment]
This issue is the icon only updates when working with people or other reagent containers.. the tray is not one of those things

gonna add a proc to update the icon and have it run when afterattack ends, and we will see if that works as a fix for everything with droppers

**Comment by FlavoredCactus** [comment]
I fixed this with
