### ISSUE TITLE
Flatoftheblade's Freeform Module Bug Report

### ISSUE THREAD

**Issue by FlavoredCactus** [Spoffy/LLA-Station-13#335]
:cactus: Copy pasting from: http://www.llagaming.net/forums/threads/freeform-module-bug-report.4235/ :cactus: 

Objects or Mechanics Involved: Using freeform module.

Brief Description (include as much detail as possible): No window pops up allowing me to write any laws.

What did you expect to happen?: A window to pop up when I interacted with the module, which would allow me to write a law.

What happened instead?: Absolutely nothing.

Has this occurred before?: Yes.

What were you doing beforehand?: Turned off turrets, entered AI upload, picked up module.

Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.): I picked up the module into my active hand and clicked it several times, switched to my inactive hand and clicked it several times, transferred the module to my other hand and clicked it several times with that hand active, switched to inactive hand and clicked it several times again, right-clicked to see if I could somehow interact with it from there but could only examine, checked object tab but there was nothing useful. Nothing I did opened up a window to write the law, or had any effect at all for that matter.

**Comment by xXTheDracheXx** [comment]
Did you try using it on the upload console?

**Comment by FlavoredCactus** [comment]
Game of telephone: "In the thread, Drache asked "Did you try using it on the upload console?"

I did, sorry for the lack of clarity. Also did nothing. Thanks for investigating this."

**Comment by RawrTaicho** [comment]
Tested and confirmed as a bug.

**Comment by Setheri** [comment]
Probable solution: Make it default to 15 if a lower number is entered
Better solution: Make it yell at and/or stun the player if they don't bother reading the dialogue and enter a number below 15.

**Comment by FlavoredCactus** [comment]
could make the default position 15
