### ISSUE TITLE
Firedome - Activities for Deadbros

### ISSUE THREAD

**Issue by RawrTaicho** [Spoffy/LLA-Station-13#338]
This was a feature we flaunted in the past as a means of keeping people who'd been taken out of the round entertained. When dead, they were given a verb that allowed them to participate in the firedome. This was essentially a Thunderdome that cycled through a few different 'round-type's' and allowed dead players to fight each other. Rounds would vary from melee free-for-all, to energy weapon team battles, and so on. When one team was left standing, or only one person remained alive in FFA, the Firedome would refresh, drop the participants back into the 'lobby area' (which was a viewing platform above the Firedome) and initiate a countdown for the next round, which was something relatively short like a minute or two.

Whilst we do still have the old code, a neater construction of this as a means of keep dead players involved in a slightly different manner would go a long way. Any additional suggestions for gamemodes should be realistic and discussed beforehand.

**Comment by FlavoredCactus** [comment]
Ooops.. i uh refrenced the wrong issue

**Comment by FlavoredCactus** [comment]
Complete in https://github.com/Spoffy/LLA-Station-13/commit/a3748021a4e70529786a873f2c11c324a3694396
