### ISSUE TITLE
Add extra sounds

### ISSUE THREAD

**Issue by IMVader** [Spoffy/LLA-Station-13#35]
Extra sounds to let you alt+tab and multitask when expecting long periods of inactivity such as these:

* When dead and placed in a cloning machine, besides the regular message. Which you won't read unless you are on the window. (Extra: Option in preferences to "automatically Re-enter corpse" once placed in a cloning machine.) A ping of sorts would work.
* When you wake up after cryo, clonning or any other moment of unconsciousness. A gasp would be nice.
* After you select an option in the IC tab, such as "Meditate" or maybe a reworked "Rest", so you are warned if anyone/thing interacts with you, such as trying to steal your ID, moving you or the likes.

**Comment by FlavoredCactus** [comment]
this (and other suggestions should be brought to the forums.
