### ISSUE TITLE
Parapen Bug

### ISSUE THREAD

**Issue by Vynergy** [Spoffy/LLA-Station-13#57]
Objects or Mechanics Involved: Parapen
Brief Description (include as much detail as possible): As a double agent, I chose a parapen as one of my items. When I managed to find my target I quickly stuck him with it. Although he fell to the ground immediately, he could still harm me. He was able to harm me for a good 10 seconds after he was supposebly "stunned." This led to my death. 
What did you expect to happen?: I expected him to be stunned.
What happened instead?: He was clearly not stunned although he was on the floor and drooling. 
Has this occurred before?: First time this has occurred to me
What were you doing beforehand?: Simply walking around

**Comment by Setheri** [comment]
So, in hindsight, I'm fairly certain this is an incarnation of the bug where certain types of dropping to the floor won't drop whats in your hand.
