### ISSUE TITLE
Remove AI's access to Plasma

### ISSUE THREAD

**Issue by Magoca** [Spoffy/LLA-Station-13#59]
Simply, disallow the AI access to plasma by removing the pump to the plasma chamber in atmospherics. 

Just leave it disconnected from the system, so it'll require some manual setup to be able to pump into the mix. That way it'll require an engineering cyborg with a bit of know-how to be able to setup.

**Comment by FlavoredCactus** [comment]
this (and other suggestions should be brought to the forums.
