### ISSUE TITLE
"A-help Panel" for Admins

### ISSUE THREAD

**Issue by LLAJWise** [Spoffy/LLA-Station-13#69]
# A-helps
## The Problem
Though I don't hear it brought up specifically very often, I don't think there is anyone with experience adminning on an SS13 server who can argue that the current system of a-helps is not a complete and utter mess. Currently, when an a-helps is sent, it pops up in the admins' chat window, heralded by that annoying bloop sound we all know so well, and is then often swept away by the constant stream of information which is presented to us. The chat tabs have helped immensely with this issue, however they are more of a band-aid than a real solution for this problem (which is fine, as they weren't intended to specifically handle the mess which we call "a-helps"). More requests for help are missed than should be the case, and handling cases can be slow and tedious due to having to having to skip all around your chat logs in order to review things that people have sent you. Anyone who jumps on the server halfway through the round has missed every a-help that was sent before they arrived, and their only hope for handling these cases is to try and get people to resend their a-helps.
## The Solution
I would like to suggest that in addition to having a-helps pop up in the chat window (and harass us with their cacophony of bloops), that we have an official "A-help Panel" which would be used to review a-helps which have been sent. This panel would contain a multitude of helpful information when dealing with cases, and most importantly, would help to organize the mess that has to be waded through with each and every case. To start, I would like to provide a mock-up of what I have in mind here:

Case Number | Case Status | Time Sent | Sender | Message | Names Mentioned | Last Attack Log
---- | ----------- | --------- | ------ | ------- | --------------- | ---------------
1 | **OPEN/TAKEN/HANDLED** - AdminName(PM) - Start Time: [time] - End Time: [time] - *View Conversation* - *Close/Reopen* | [time] | SenderName(SenderCkey)(PM)(?) | Message Contents | Names mentioned in a-help | The sender's last attack log at the time of sending
Now to explain the specifics of this menu:
#### The Panel Itself
1. Case Number
    * What it says on the tin - displays the "number" of each specific a-help in order to help navigate the menu
2. Case Status
    * After being sent, every a-help is initially set to "OPEN", which means that no admin has yet officially indicated that they are taking the case
    * While a case is "OPEN", admins would be able to click on a "Take Case" button in this section of the menu, which would change the status of the case to "TAKEN", mark down the time at which the case was taken, and send a notification to the person who sent the a-help to let them know that it is being looked into
    * While a case is "TAKEN", in addition to the name of the admin who took the case, and the time at which they took it, there would be two options available under "Case Status" - "Close" and "View Conversation" (Which will be covered in more detail shortly)
    * Pressing "Close" will "officially" end the case by changing the status of the case to "HANDLED", marking down the time at which the case was closed, however there will be an option to "Reopen" a case, in addition to the option to "View Conversation"
3. Time Sent
    * Once again, what it says on the tin - the time at which the a-help was sent
4. Sender
    * The name of the person who sent the a-help, their ckey, their antag status, an option to PM them, and an option to display the quick information output currently available through a-helps
5. Message
    * The contents of the message which was sent in the a-help
6. Names Mentioned
    * A-helps currently have some functionality to recognize names and allow admins to quickly get information about people mentioned in a-helps
    * This system would work in essentially the same way, however instead of inserting the prompts directly into the message which was sent, all names which were mentioned would be listed in this section of the menu
    * In addition to their IC names, it would also display the ckey of these people, their antag status, an option to PM them, and the same "information blurb" already used by a-helps
    * If only part of a name is listed (i.e. George), and there are multiple people who have that name "part" in their name (George Melons, George Foreman), then it would display both names with an "OR" between them
7. Last Attack Log
    * Last but not least, the "Last Attack Log" section would provide the last entry to the sender's attack log at the time that they sent their a-help

#### Additional Features
1. "View Conversation"
    * The previously mentioned "View Conversation" button would be an additional feature to help organize cases based on relative information
    * Clicking the button would open up a small window which would only display PM's which are "associated" with that particular case
    * PM'ing someone via a PM prompt which is in the menu (i.e. next to the sender's name, or next to the name of someone who was "mentioned" in the a-help) would automatically "associate" that PM, and any responses to it, with that particular case
    * In addition, by opening up the "View Conversation" window, you would have the option to PM anyone and associate that PM, and any responses to it, with that case
    * Note: Something like this would obviously be pretty touch and go as far as usefulness goes, however it would provide more organization than we currently have
2. Database Compatibility
    * At the end of each round, all a-helps / cases in the a-help panel would be exported to their own section in the database
    * Any cases which remain "OPEN" at the end of a round would have their status changed to "MISSED" when they are added to the database
    * Though it may take some extra work, it may also be worth it to maintain the "View Conversation" functionality, and upload the entire "Conversation" to the database for review as well

## Conclusion
The current system of a-helps is, on its own, disorganized, difficult to use at times, and in many ways, just plain broken. A more organized system, with the ability for admins who join a round late to see what has already been sent, with the ability to log which admins are handling which cases, the ability to see which cases have been missed, and the ability to see what has been discussed with regards to each separate case is something that would be a great help. I won't pretend that it won't be difficult to add something like this, but it would be well worth it.

**Comment by FlavoredCactus** [comment]
this (and other suggestions should be brought to the forums.
