### ISSUE TITLE
Unable to grind or blend Destroying Angel

### ISSUE THREAD

**Issue by DrChef** [Spoffy/LLA-Station-13#76]
Objects or Mechanics Involved: Destroying Angel Plant
Brief Description (include as much detail as possible): When you mutate weeds, there is a possibility that you can mutate Destroying Angel. On the /tg/ wiki, it states that it kills you dead, however you cant eat it, blend, or grind it for poison.
What did you expect to happen?: When you blend or grind, you're supposed to get a beaker full of deadly poisons.
What happened instead?: Nothing.
Has this occurred before?: Yes.
What were you doing beforehand?: I was growing plants. I even tried raising the potency. 
Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.):
N/A

**Comment by Setheri** [comment]
Fixed by PR #154
